US011-Create-Login-Form
dnhieu1992/GoTrip pull request #17
Opened 2021-06-07 14:18 UTC by DuongPhamViet

2021-06-07 14:51 UTC, dnhieu1992 requested changes

2021-06-07 14:51 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/App.js
> +import resetpass from './auth/login/resetpass';
Change to reset(reset)

2021-06-07 14:51 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/auth/registration/register.jsx
> +const register = () => {
Remove all register feature;tránh conflict với @chungdaotn

2021-06-08 02:19 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/App.js
> +import './login.scss';
Add to index.scss file

2021-06-08 02:21 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/App.js
> +import reset from './auth/login/reset';
remove reset component, change login name component to Login, name of the component is PascalCase

2021-06-08 02:21 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/App.js
> +        <Route path="/login/reset" component={reset} />
Remove reset route

2021-06-08 02:25 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/admin-page/bed/component/BedForm.jsx
>                      {/* <label>Description</label>
remove code not use

2021-06-08 02:26 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/auth/login/reset.jsx
> +const reset = () => {
Component name is PascalCase

2021-06-08 02:27 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/index.scss
> +@import "./login.scss";
move login.scss to /shared/sass/components/login

2021-06-09 02:13 UTC, DuongPhamViet commented on B-CLIENT/gotrip/src/App.js
> +import './login.scss';
done

2021-06-09 02:14 UTC, DuongPhamViet commented on B-CLIENT/gotrip/src/App.js
> +import reset from './auth/login/reset';
done

2021-06-09 02:14 UTC, DuongPhamViet commented on B-CLIENT/gotrip/src/App.js
> +        <Route path="/login/reset" component={reset} />
done

2021-06-09 02:14 UTC, DuongPhamViet commented on B-CLIENT/gotrip/src/admin-page/bed/component/BedForm.jsx
>                      {/* <label>Description</label>
done

2021-06-09 02:14 UTC, DuongPhamViet commented on B-CLIENT/gotrip/src/auth/login/reset.jsx
> +const reset = () => {
done

2021-06-09 02:14 UTC, DuongPhamViet commented on B-CLIENT/gotrip/src/index.scss
> +@import "./login.scss";
done

2021-06-10 03:21 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/auth/login/login.jsx
> +const Login = () => {
name of file same with name of component(PasscalCase)

2021-06-10 03:21 UTC, dnhieu1992 commented on B-CLIENT/gotrip/src/auth/login/reset.jsx
> +const Reset = () => {
Name of file same with name of component(PasscalCase)

2021-06-10 07:05 UTC, DuongPhamViet commented on B-CLIENT/gotrip/src/auth/login/reset.jsx
> +const Reset = () => {
done

2021-06-10 07:05 UTC, DuongPhamViet commented on B-CLIENT/gotrip/src/auth/login/login.jsx
> +const Login = () => {
done

2021-06-11 06:24 UTC, merged